version: '3.7'

services:
  worker_os:
    container_name: hldf_docker_celery_workeros
    build:
      context: .
      dockerfile: ./volumes/monica_celery/DockerFile_Alpine
    volumes:
      - ./volume/monica_celery/var/run/celery:/var/run/celery
